version: "3.8"

services:
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 11002:3306
        environment:
            MYSQL_USER: wp
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: wordpress
            MYSQL_PASSWORD: 123
        command: [
            "--default_authentication_plugin=mysql_native_password",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci"
        ]

    wordpress:
        image: wordpress:latest
        depends_on:
            - mysql
        restart: always
        ports:
            - 11001:80
        links:
            - mysql:db
        build:
            context: ./docker
            dockerfile: Dockerfile-wordpress
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: 123
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_CONFIG_EXTRA: |
                define("FS_METHOD", "direct");
                define("WP_DEBUG", true);
        volumes:
            - ./var/plugins:/var/www/html/wp-content/plugins
            - ./var/upload:/var/www/html/wp-content/uploads
